name: telemetry
on:
  push:
    branches: [main]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "currentP95: 1800" >> spec/sla.yaml
          echo "currentScore: 85" >> spec/sla.yaml
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: telemetry update"